name: Project Board Automation - Pyrsia Development

on:
  issues:
    types: [opened, reopened]

jobs:
  triage-new-issues:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' &&
      (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            triage
            website
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Pyrsia Development
          action: add
          column: Backlog for the Demo
          repo-token: ${{ secrets.ORG_ACCESS_TOKEN }}
